### ISSUE TITLE
Intro screen / disclaimer

### ISSUE THREAD

**Issue by jinchung** [balance-io/balance-wallet#26]

**Comment by ricburton** [comment]
I had a rough version working but got stuck on this build error:

```
> BalanceWallet@0.0.1 ios /Users/richardburton/balance-wallet
> react-native run-ios --simulator='iPhone X'

util.js:969
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.inherits (util.js:969:11)
    at Object.<anonymous> (/Users/richardburton/balance-wallet/node_modules/are-we-there-yet/tracker-stream.js:14:6)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/richardburton/balance-wallet/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```

It seems related to this module: https://www.npmjs.com/package/are-we-there-yet

It happened around the time I was trying to add `react-native-button`: https://www.npmjs.com/package/react-native-button

Work is here: https://github.com/balance-io/balance-wallet/tree/warning

**Comment by mikedemarais** [comment]
@ricburton yo! i already built out this view! its totally done!

that error you are seeing could possibly be from the `react-native-button` package you tried to install, but we dont need that package! i built us our own `button` component!

**Comment by ricburton** [comment]
Hellll yeah. I was just playing around and learning :)

Richard
